import {
  BookOpen,
  ChefHat,
  Coins,
  FlaskConical,
  GraduationCap,
  House,
  Keyboard,
  LifeBuoy,
  Map,
  Network,
  Puzzle,
  Zap,
} from "@lucide/vue";
import type { NavSection } from "./types/nav";

export const sections: NavSection[] = [
  {
    slug: "welcome",
    title: "Welcome",
    path: "/",
    icon: House,
    accent: "home",
    tagline: "Start here",
    description:
      "What Claudeverse is, who it's for, and the fastest path in based on your experience.",
    estReadTime: "3 min",
    children: [
      { title: "The state of Claude Code", path: "/#state-of-the-art" },
      { title: "How to use this guide", path: "/#how-to-use" },
      { title: "What is Claudeverse", path: "/#what-is-claudeverse" },
      { title: "Who it's for", path: "/#audience" },
    ],
  },
  {
    slug: "foundations",
    title: "Foundations",
    path: "/foundations",
    icon: BookOpen,
    accent: "foundations",
    tagline: "Mental model + setup",
    description:
      "The mindset shift, how the harness works, the context window, setup, CLAUDE.md, models, and safety.",
    estReadTime: "25 min",
    children: [
      { title: "The Mental Model Shift", path: "/foundations#mental-model" },
      { title: "How Claude Code Works", path: "/foundations#how-it-works" },
      { title: "The Context Window", path: "/foundations#context-window" },
      { title: "Setup & Installation", path: "/foundations#setup" },
      { title: "CLAUDE.md Deep Dive", path: "/foundations#claude-md" },
      { title: "Hiding Files from Claude", path: "/foundations#hiding-files" },
      { title: "Configuration Layers", path: "/foundations#config" },
      { title: "Models", path: "/foundations#models" },
      { title: "Permissions & Safety", path: "/foundations#safety" },
    ],
  },
  {
    slug: "workflows",
    title: "Workflows",
    path: "/workflows",
    icon: Zap,
    accent: "workflows",
    tagline: "Plan → execute",
    description:
      "The 4-phase workflow, Plan Mode, feedback loops, prompt precision, session management, and checkpointing.",
    estReadTime: "20 min",
    children: [
      { title: "The 4-Phase Workflow", path: "/workflows#four-phase" },
      { title: "Plan Mode", path: "/workflows#plan-mode" },
      { title: "When to Skip Planning", path: "/workflows#skip-plan" },
      { title: "Feedback Loops", path: "/workflows#feedback" },
      { title: "Prompt Precision", path: "/workflows#prompts" },
      { title: "Session Management", path: "/workflows#sessions" },
      { title: "Checkpointing", path: "/workflows#checkpoints" },
      { title: "The Big Prompt Pattern", path: "/workflows#big-prompt" },
      { title: "Best of N", path: "/workflows#best-of-n" },
      { title: "Context Handoff", path: "/workflows#handoff" },
    ],
  },
  {
    slug: "extensions",
    title: "Extensions",
    path: "/extensions",
    icon: Puzzle,
    accent: "extensions",
    tagline: "The 6 layers",
    description:
      "Skills, Commands, Hooks, Subagents, Agent Teams, MCP, Plugins, and LSP — when to reach for each.",
    estReadTime: "35 min",
    children: [
      { title: "Decision Framework", path: "/extensions#decision" },
      { title: "Skills", path: "/extensions#skills" },
      { title: "Commands", path: "/extensions#commands" },
      { title: "Hooks", path: "/extensions#hooks" },
      { title: "Subagents", path: "/extensions#subagents" },
      { title: "Agent Teams", path: "/extensions#agent-teams" },
      { title: "MCP", path: "/extensions#mcp" },
      { title: "Plugins", path: "/extensions#plugins" },
      { title: "LSP", path: "/extensions#lsp" },
    ],
  },
  {
    slug: "tokens",
    title: "Token Mastery",
    path: "/tokens",
    icon: Coins,
    accent: "tokens",
    tagline: "Cut usage in half",
    description:
      "Why tokens matter, the three highest-impact fixes, monitoring, CLAUDE.md diet, model routing, and team cost control.",
    estReadTime: "20 min",
    children: [
      { title: "Why Tokens Matter", path: "/tokens#why" },
      { title: "The 3 Fixes", path: "/tokens#three-fixes" },
      { title: "Monitor Your Usage", path: "/tokens#monitor" },
      { title: "CLAUDE.md Diet", path: "/tokens#diet" },
      { title: "Tiered Architecture", path: "/tokens#tiered" },
      { title: "Compact Strategies", path: "/tokens#compact" },
      { title: "Model Routing", path: "/tokens#routing" },
      { title: "Subagent Economics", path: "/tokens#subagent-econ" },
      { title: "Hook-Based Output Control", path: "/tokens#hook-output" },
      { title: "Team Cost Management", path: "/tokens#team-cost" },
      { title: "Session Template", path: "/tokens#template" },
    ],
  },
  {
    slug: "orchestration",
    title: "Orchestration",
    path: "/orchestration",
    icon: Network,
    accent: "orchestration",
    tagline: "Scale beyond one session",
    description:
      "Multi-agent patterns, the 3-tier orchestrator landscape, Agent Teams, worktrees, AGENTS.md, and quality gates.",
    estReadTime: "25 min",
    children: [
      { title: "When to Scale Up", path: "/orchestration#when" },
      { title: "The 3 Tiers", path: "/orchestration#tiers" },
      { title: "Subagents → Teams", path: "/orchestration#graduation" },
      { title: "Git Worktrees", path: "/orchestration#worktrees" },
      { title: "Conductor vs Orchestrator", path: "/orchestration#models" },
      { title: "Agent Teams Deep Dive", path: "/orchestration#teams" },
      { title: "Quality Gates", path: "/orchestration#gates" },
      { title: "AGENTS.md", path: "/orchestration#agents-md" },
      { title: "Token Economics", path: "/orchestration#econ" },
      { title: "External Orchestrators", path: "/orchestration#external" },
    ],
  },
  {
    slug: "evals",
    title: "Evals",
    path: "/evals",
    icon: FlaskConical,
    accent: "evals",
    tagline: "Test your agents",
    description:
      "Why evals matter, golden datasets, LLM-as-judge, regression suites, Anthropic's eval SDK, CI integration, and the cost of testing agent output.",
    estReadTime: "20 min",
    children: [
      { title: "Why Evals Matter", path: "/evals#why" },
      { title: "Golden Datasets", path: "/evals#golden" },
      { title: "LLM-as-Judge", path: "/evals#judge" },
      { title: "Regression Suites", path: "/evals#regression" },
      { title: "Anthropic's Eval SDK", path: "/evals#sdk" },
      { title: "Running in CI", path: "/evals#ci" },
      { title: "The Cost of Evals", path: "/evals#cost" },
    ],
  },
  {
    slug: "recipes",
    title: "Recipes",
    path: "/recipes",
    icon: ChefHat,
    accent: "recipes",
    tagline: "Scenario cookbook",
    description:
      "Real-world scenarios solved end-to-end: adding auth, refactoring a monolith, onboarding an engineer, migrating a codebase, and automating reviews.",
    estReadTime: "30 min",
    children: [
      { title: "Add Auth to a Web App", path: "/recipes#auth" },
      { title: "Refactor a Monolith", path: "/recipes#refactor" },
      { title: "Onboard a New Engineer", path: "/recipes#onboard" },
      { title: "Migrate a Codebase", path: "/recipes#migrate" },
      { title: "Automate Code Reviews", path: "/recipes#reviews" },
      { title: "Ship a Feature in a Worktree", path: "/recipes#feature" },
    ],
  },
  {
    slug: "troubleshooting",
    title: "Troubleshooting",
    path: "/troubleshooting",
    icon: LifeBuoy,
    accent: "troubleshooting",
    tagline: "When things break",
    description:
      "Common failure modes and how to fix them: context issues, hooks that don't fire, MCP connection errors, runaway tokens, rate limits, and auth problems.",
    estReadTime: "10 min",
    children: [
      {
        title: "Claude Can't See My File",
        path: "/troubleshooting#missing-file",
      },
      {
        title: "Out of Context Errors",
        path: "/troubleshooting#out-of-context",
      },
      { title: "Hook Didn't Fire", path: "/troubleshooting#hook" },
      { title: "MCP Won't Connect", path: "/troubleshooting#mcp" },
      { title: "Tokens Exploding", path: "/troubleshooting#tokens" },
      { title: "Rate Limits", path: "/troubleshooting#rate-limits" },
      { title: "Auth & Login Issues", path: "/troubleshooting#auth" },
    ],
  },
  {
    slug: "resources",
    title: "Resources",
    path: "/resources",
    icon: Map,
    accent: "resources",
    tagline: "Courses, repos, articles",
    description:
      "Curated official docs, free/paid courses, essential GitHub repos, blog posts, communities, and newsletters.",
    estReadTime: "10 min",
    children: [
      { title: "Official & Free", path: "/resources#official" },
      { title: "Paid Courses", path: "/resources#paid" },
      { title: "Essential GitHub Repos", path: "/resources#repos" },
      { title: "Key Articles", path: "/resources#articles" },
      { title: "Communities", path: "/resources#communities" },
    ],
  },
  {
    slug: "workshops",
    title: "Workshops",
    path: "/workshops",
    icon: GraduationCap,
    accent: "workshops",
    tagline: "Learn by doing",
    description:
      "Hands-on practicals: guided build-alongs for every major Claude Code concept, plus timed challenges to sharpen your instincts.",
    estReadTime: "Pick one, ~45 min each",
    children: [
      { title: "How to use this page", path: "/workshops#how-to-use" },
      { title: "Build-Alongs", path: "/workshops#build-alongs" },
      { title: "Build 1 — CLAUDE.md from scratch", path: "/workshops#ba-claude-md" },
      { title: "Build 2 — Your first Plan Mode feature", path: "/workshops#ba-plan-mode" },
      { title: "Build 3 — Your first hook", path: "/workshops#ba-hook" },
      { title: "Build 4 — A custom slash command", path: "/workshops#ba-command" },
      { title: "Build 5 — Wire up an MCP server", path: "/workshops#ba-mcp" },
      { title: "Build 6 — A 3-agent team", path: "/workshops#ba-agents" },
      { title: "Build 7 — An eval suite", path: "/workshops#ba-evals" },
      { title: "Challenges", path: "/workshops#challenges" },
      { title: "Challenge 1 — Cost-cut 50%", path: "/workshops#ch-cost" },
      { title: "Challenge 2 — CLAUDE.md diet", path: "/workshops#ch-diet" },
      { title: "Challenge 3 — Prompt precision", path: "/workshops#ch-prompt" },
      { title: "Challenge 4 — Debug a broken hook", path: "/workshops#ch-hook" },
      { title: "Challenge 5 — Model routing", path: "/workshops#ch-routing" },
      { title: "Workshop tracks", path: "/workshops#tracks" },
    ],
  },
  {
    slug: "cheatsheet",
    title: "Cheatsheet",
    path: "/cheatsheet",
    icon: Keyboard,
    accent: "cheatsheet",
    tagline: "Quick reference",
    description:
      "Commands, keyboard shortcuts, CLI flags, file structure, and common patterns — printable.",
    estReadTime: "5 min",
    children: [
      { title: "Slash Commands", path: "/cheatsheet#commands" },
      { title: "Keyboard Shortcuts", path: "/cheatsheet#shortcuts" },
      { title: "CLI Flags", path: "/cheatsheet#flags" },
      { title: "File Structure", path: "/cheatsheet#files" },
      { title: "Patterns", path: "/cheatsheet#patterns" },
    ],
  },
];

export const findSection = (path: string): NavSection | undefined => {
  const basePath = path.split("#")[0] || "/";
  return sections.find((s) => s.path === basePath);
};
